on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - id: variables
        run: |
          REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          VERSION=$(cat manifest.json | jq -r .version)
          echo "ZIPFILE_NAME=/tmp/${REPOSITORY_NAME}-${VERSION}.zip" >> $GITHUB_OUTPUT
          echo "TAG=v${VERSION}" >> $GITHUB_OUTPUT

      - name: zip
        run: zip -r "${{ steps.variables.outputs.ZIPFILE_NAME }}" * -x browser_specific_settings.json
    
      - name: remove release and tag if exists
        run: |
          gh release delete ${{ steps.variables.outputs.TAG }} --cleanup-tag --yes || true
          git push --delete origin tag ${{ steps.variables.outputs.TAG }}

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.variables.outputs.ZIPFILE_NAME }}
          tag_name: ${{ steps.variables.outputs.TAG }}
          generate_release_notes: true
